In [1]:
import pandas as pd
import numpy as np

**Read in data from cleaning part 1**

In [427]:
Weather = pd.read_csv('Weather.csv')
Income = pd.read_csv('Income.csv')
Population = pd.read_csv('Population.csv')
Population2 = pd.read_csv('Population2.csv')
Storm_Events = pd.read_csv('Storm_Events.csv')
Gas_Prices = pd.read_csv('Gas_Price.csv')
Crimes = pd.read_csv('Crimes.csv')
SPI = pd.read_csv('SPI.csv')
Health = pd.read_csv('Health.csv')

### Weather

In [428]:
Weather.head()

     State     TAVG     TMIN     TMAX        Date  Year  Month
0  Alabama     40.8     30.8     50.9  1994-01-01  1994      1
1  Alabama     50.3     38.3     62.2  1994-02-01  1994      2
2  Alabama     55.8     42.3     69.2  1994-03-01  1994      3
3  Alabama     64.7     51.3     78.2  1994-04-01  1994      4
4  Alabama     68.4     56.2     80.6  1994-05-01  1994      5

In [429]:
Weather.columns

Index(['State', '   TAVG', '   TMIN', '   TMAX', 'Date', 'Year', 'Month'], dtype='object')

**Group by year**

In [430]:
Weather_Year = Weather.groupby(['Year', 'State'])['   TAVG', '   TMIN', '   TMAX'].mean()
Weather_Year = pd.DataFrame(Weather_Year.to_records())

**Group by month**

In [431]:
Weather_Month = Weather.groupby(['Year', 'Month', 'State'])['   TAVG', '   TMIN', '   TMAX'].mean()
Weather_Month = pd.DataFrame(Weather_Month.to_records())

In [432]:
Income.head()

           State  Median_Income  Year        Date
0  United States        59039.0  2016  2016-01-01
1        Alabama        47221.0  2016  2016-01-01
2         Alaska        75723.0  2016  2016-01-01
3        Arizona        57100.0  2016  2016-01-01
4       Arkansas        45907.0  2016  2016-01-01

### Population

In [433]:
Population.head()

   Year State_Abbrev  Population
0  1994           AK      603308
1  1994           AL     4260229
2  1994           AR     2494019
3  1994           AZ     4245089
4  1994           CA    31484435

In [434]:
Population2.head()

   Year State_Abbrev  Race  Sex  Age  Population   Age_Group
0  1994           AL     1    1    0         226  Child/Teen
1  1994           AL     1    1    1         917  Child/Teen
2  1994           AL     1    1    2        1235  Child/Teen
3  1994           AL     1    1    3        1333  Child/Teen
4  1994           AL     1    1    4        1114  Child/Teen

### Storm_Events

In [435]:
Storm_Events.head()

,index,STATE,YEAR,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Month,Date
0,0,ALABAMA,1994,Tornado,20,0,0,0,5000000,0,3,1994-03-01
1,1,ALABAMA,1994,Thunderstorm Wind,0,0,0,0,0,0,5,1994-05-01
2,2,ALABAMA,1994,Thunderstorm Wind,0,0,0,0,500000,0,6,1994-06-01
3,3,ALABAMA,1994,Hail,0,0,0,0,0,0,5,1994-05-01
4,4,ALABAMA,1994,Hail,0,0,0,0,0,0,3,1994-03-01

**Rename columns to match other datasets**

In [436]:
Storm_Events.rename(columns={'STATE':'State'}, inplace=True)

In [437]:
Storm_Events.rename(columns={'YEAR':'Year'}, inplace=True)

In [438]:
Storm_Events['State'] = Storm_Events['State'].str.lower().str.title()

**Check how many events of each type**

In [439]:
Storm_Events['EVENT_TYPE'].value_counts()

Thunderstorm Wind                 152170
Hail                              123599
Flash Flood                        41914
Winter Weather                     30774
Winter Storm                       29523
High Wind                          28698
Flood                              24174
Drought                            22156
Heavy Snow                         21893
Tornado                            15867
Marine Thunderstorm Wind           11813
Heavy Rain                         11179
Strong Wind                        10208
Lightning                           6677
Dense Fog                           6254
Extreme Cold/Wind Chill             6117
Blizzard                            5989
Frost/Freeze                        5840
Heat                                5832
Excessive Heat                      4974
High Surf                           4630
Cold/Wind Chill                     4100
Funnel Cloud                        3963
Ice Storm                           3500
Wildfire                            3021
Waterspout                          2106
Lake-Effect Snow                    1715
Tropical Storm                      1669
Coastal Flood                       1410
Rip Current                          659
                                   ...
Debris Flow                          279
Tropical Depression                  273
Sleet                                260
Freezing Fog                         237
Hurricane                            127
Dust Devil                           110
Marine Strong Wind                    83
Lakeshore Flood                       42
Seiche                                41
Tsunami                               30
Marine Tropical Storm                 29
Dense Smoke                           18
Marine Hurricane/Typhoon              16
Sneakerwave                           10
Marine Dense Fog                       5
Volcanic Ashfall                       4
THUNDERSTORM WIND/ TREES               3
THUNDERSTORM WINDS/ FLOOD              2
THUNDERSTORM WINDS FUNNEL CLOU         2
THUNDERSTORM WINDS LIGHTNING           2
Marine Lightning                       1
Marine Tropical Depression             1
THUNDERSTORM WINDS/FLOODING            1
THUNDERSTORM WINDS/FLASH FLOOD         1
HAIL/ICY ROADS                         1
THUNDERSTORM WINDS/HEAVY RAIN          1
TORNADO/WATERSPOUT                     1
HAIL FLOODING                          1
THUNDERSTORM WINDS HEAVY RAIN          1
THUNDERSTORM WIND/ TREE                1
Name: EVENT_TYPE, Length: 68, dtype: int64

**Will include every category since DAMAGE_PROPERTY and DAMAGE_CROPS wouldn't be adjusted for otherwise.**

**Convert the Event column to dummy variables**

In [440]:
Events = pd.get_dummies(Storm_Events['EVENT_TYPE'])
Storm_Events = pd.concat([Storm_Events, Events], axis = 1)

In [441]:
del Storm_Events['EVENT_TYPE']
del Storm_Events['index']

**Change display settings so can see all columns**

In [442]:
pd.set_option('display.max_columns', 200)

In [443]:
Storm_Events.head()

,State,Year,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Month,Date,Astronomical Low Tide,Avalanche,Blizzard,Coastal Flood,Cold/Wind Chill,Debris Flow,Dense Fog,Dense Smoke,Drought,Dust Devil,Dust Storm,Excessive Heat,Extreme Cold/Wind Chill,Flash Flood,Flood,Freezing Fog,Frost/Freeze,Funnel Cloud,HAIL FLOODING,HAIL/ICY ROADS,Hail,Heat,Heavy Rain,Heavy Snow,High Surf,High Wind,Hurricane,Hurricane (Typhoon),Ice Storm,Lake-Effect Snow,Lakeshore Flood,Landslide,Lightning,Marine Dense Fog,Marine Hail,Marine High Wind,Marine Hurricane/Typhoon,Marine Lightning,Marine Strong Wind,Marine Thunderstorm Wind,Marine Tropical Depression,Marine Tropical Storm,Rip Current,Seiche,Sleet,Sneakerwave,Storm Surge/Tide,Strong Wind,THUNDERSTORM WIND/ TREE,THUNDERSTORM WIND/ TREES,THUNDERSTORM WINDS FUNNEL CLOU,THUNDERSTORM WINDS HEAVY RAIN,THUNDERSTORM WINDS LIGHTNING,THUNDERSTORM WINDS/ FLOOD,THUNDERSTORM WINDS/FLASH FLOOD,THUNDERSTORM WINDS/FLOODING,THUNDERSTORM WINDS/HEAVY RAIN,TORNADO/WATERSPOUT,Thunderstorm Wind,Tornado,Tropical Depression,Tropical Storm,Tsunami,Volcanic Ashfall,Waterspout,Wildfire,Winter Storm,Winter Weather
0,Alabama,1994,20,0,0,0,5000000,0,3,1994-03-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,Alabama,1994,0,0,0,0,0,0,5,1994-05-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,Alabama,1994,0,0,0,0,500000,0,6,1994-06-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,Alabama,1994,0,0,0,0,0,0,5,1994-05-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Alabama,1994,0,0,0,0,0,0,3,1994-03-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Group by year**

In [444]:
Storm1 = Storm_Events.copy()

In [445]:
Storm1 = Storm1.drop(['Month', 'Date'], axis = 1)

In [446]:
Storm1.head()

,State,Year,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Astronomical Low Tide,Avalanche,Blizzard,Coastal Flood,Cold/Wind Chill,Debris Flow,Dense Fog,Dense Smoke,Drought,Dust Devil,Dust Storm,Excessive Heat,Extreme Cold/Wind Chill,Flash Flood,Flood,Freezing Fog,Frost/Freeze,Funnel Cloud,HAIL FLOODING,HAIL/ICY ROADS,Hail,Heat,Heavy Rain,Heavy Snow,High Surf,High Wind,Hurricane,Hurricane (Typhoon),Ice Storm,Lake-Effect Snow,Lakeshore Flood,Landslide,Lightning,Marine Dense Fog,Marine Hail,Marine High Wind,Marine Hurricane/Typhoon,Marine Lightning,Marine Strong Wind,Marine Thunderstorm Wind,Marine Tropical Depression,Marine Tropical Storm,Rip Current,Seiche,Sleet,Sneakerwave,Storm Surge/Tide,Strong Wind,THUNDERSTORM WIND/ TREE,THUNDERSTORM WIND/ TREES,THUNDERSTORM WINDS FUNNEL CLOU,THUNDERSTORM WINDS HEAVY RAIN,THUNDERSTORM WINDS LIGHTNING,THUNDERSTORM WINDS/ FLOOD,THUNDERSTORM WINDS/FLASH FLOOD,THUNDERSTORM WINDS/FLOODING,THUNDERSTORM WINDS/HEAVY RAIN,TORNADO/WATERSPOUT,Thunderstorm Wind,Tornado,Tropical Depression,Tropical Storm,Tsunami,Volcanic Ashfall,Waterspout,Wildfire,Winter Storm,Winter Weather
0,Alabama,1994,20,0,0,0,5000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,Alabama,1994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,Alabama,1994,0,0,0,0,500000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,Alabama,1994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Alabama,1994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [447]:
Storm1 = Storm1.groupby(['Year', 'State']).sum()
Storm1 = pd.DataFrame(Storm1.to_records())

In [448]:
Storm_Year = Storm1.copy()

**Group by month**

In [495]:
Storm1 = Storm_Events.copy()

In [496]:
Storm1.head()

,State,Year,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Month,Date,Astronomical Low Tide,Avalanche,Blizzard,Coastal Flood,Cold/Wind Chill,Debris Flow,Dense Fog,Dense Smoke,Drought,Dust Devil,Dust Storm,Excessive Heat,Extreme Cold/Wind Chill,Flash Flood,Flood,Freezing Fog,Frost/Freeze,Funnel Cloud,HAIL FLOODING,HAIL/ICY ROADS,Hail,Heat,Heavy Rain,Heavy Snow,High Surf,High Wind,Hurricane,Hurricane (Typhoon),Ice Storm,Lake-Effect Snow,Lakeshore Flood,Landslide,Lightning,Marine Dense Fog,Marine Hail,Marine High Wind,Marine Hurricane/Typhoon,Marine Lightning,Marine Strong Wind,Marine Thunderstorm Wind,Marine Tropical Depression,Marine Tropical Storm,Rip Current,Seiche,Sleet,Sneakerwave,Storm Surge/Tide,Strong Wind,THUNDERSTORM WIND/ TREE,THUNDERSTORM WIND/ TREES,THUNDERSTORM WINDS FUNNEL CLOU,THUNDERSTORM WINDS HEAVY RAIN,THUNDERSTORM WINDS LIGHTNING,THUNDERSTORM WINDS/ FLOOD,THUNDERSTORM WINDS/FLASH FLOOD,THUNDERSTORM WINDS/FLOODING,THUNDERSTORM WINDS/HEAVY RAIN,TORNADO/WATERSPOUT,Thunderstorm Wind,Tornado,Tropical Depression,Tropical Storm,Tsunami,Volcanic Ashfall,Waterspout,Wildfire,Winter Storm,Winter Weather
0,Alabama,1994,20,0,0,0,5000000,0,3,1994-03-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,Alabama,1994,0,0,0,0,0,0,5,1994-05-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,Alabama,1994,0,0,0,0,500000,0,6,1994-06-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,Alabama,1994,0,0,0,0,0,0,5,1994-05-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Alabama,1994,0,0,0,0,0,0,3,1994-03-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [497]:
del Storm1['Date']

In [498]:
Storm1 = Storm1.groupby(['Year', 'Month', 'State']).sum()
Storm1 = pd.DataFrame(Storm1.to_records())

In [499]:
Storm_Month = Storm1.copy()

### Gas_Prices

In [455]:
Gas_Prices.head()

  State_Abbrev  Year  Gas_Per_Gallon
0           AK  1994        1.307750
1           AL  1994        1.069864
2           AR  1994        1.073600
3           AZ  1994        1.193166
4           CA  1994        1.133383

### Crimes

In [456]:
Crimes.head()

,Year,State_Abbrev,violent_crime,homicide,rape_legacy,robbery,aggravated_assault,property_crime,burglary,larceny,motor_vehicle_theft
0,1995,AL,26894,475,1350,7900,17169,179294,43586,120967,14741
1,1996,AL,24159,444,1397,7124,15194,181803,42821,123350,15632
2,1997,AL,24379,426,1396,6931,15626,186809,43786,127616,15407
3,1998,AL,22286,354,1443,5698,14791,177779,41965,120943,14871
4,1999,AL,21421,345,1513,5297,14266,171398,38648,119616,13134

### SPI

In [457]:
SPI.head()

  State  Year  Month       SPI
0    AL  1994      1  0.211791
1    AL  1994      2  0.110149
2    AL  1994      3  0.547612
3    AL  1994      4 -0.008657
4    AL  1994      5 -0.308060

**Rename column to match other datasets**

In [458]:
SPI.rename(columns={'State':'State_Abbrev'}, inplace=True)

**Group by year**

In [459]:
SPI_Year = SPI.groupby(['State_Abbrev', 'Year'])[['SPI']].mean()
SPI_Year = pd.DataFrame(SPI_Year.to_records())

**Save original as by month**

In [460]:
SPI_Month = SPI.copy()

### Health

In [461]:
Health.head()

   Year       State   PHYSHLTH   MENTHLTH
0  1994     Alabama  13.255814  13.930233
1  1994      Alaska   8.027132   9.430233
2  1994     Arizona  10.468468  10.387387
3  1994    Arkansas  11.447489  11.703196
4  1994  California   9.182464   9.693128

### Create Year combined dataframe

**Left joins are used so that no data is lost in order to be able to create year visualization for any data**

In [475]:
df = pd.merge(left = Weather_Year, right = Income, on = ['State', 'Year'], how = 'right')

In [476]:
df2 = pd.merge(left = df, right = Storm_Year, on = ['State', 'Year'], how = 'left')

In [477]:
df3 = pd.merge(left = df2, right = Health, on = ['State', 'Year'], how = 'left')

**Create Conversion scheme to make State_Abbrev column for State column in the dataframe to match other datasets**

In [478]:
StateConversion = {
    'District of Columbia': 'DC',
    'Alabama': 'AL',
    'Montana': 'MT',
    'Alaska': 'AK',
    'Nebraska': 'NE',
    'Arizona': 'AZ',
    'Nevada': 'NV',
    'Arkansas': 'AR',
    'New Hampshire': 'NH',
    'California': 'CA',
    'New Jersey': 'NJ',
    'Colorado': 'CO',
    'New Mexico': 'NM',
    'Connecticut': 'CT',
    'New York': 'NY',
    'Delaware': 'DE',
    'North Carolina': 'NC',
    'Florida': 'FL',
    'North Dakota': 'ND',
    'Georgia': 'GA',
    'Ohio': 'OH',
    'Hawaii': 'HI',
    'Oklahoma': 'OK',
    'Idaho': 'ID',
    'Oregon': 'OR',
    'Illinois': 'IL',
    'Pennsylvania': 'PA',
    'Indiana': 'IN',
    'Rhode Island': 'RI',
    'Iowa': 'IA',
    'South Carolina': 'SC',
    'Kansas': 'KS',
    'South Dakota': 'SD',
    'Kentucky': 'KY',
    'Tennessee': 'TN',
    'Louisiana': 'LA',
    'Texas': 'TX',
    'Maine': 'ME',
    'Utah': 'UT',
    'Maryland': 'MD',
    'Vermont': 'VT',
    'Massachusetts': 'MA',
    'Virginia': 'VA',
    'Michigan': 'MI',
    'Washington': 'WA',
    'Minnesota': 'MN',
    'West Virginia': 'WV',
    'Mississippi': 'MS',
    'Wisconsin': 'WI',
    'Missouri': 'MO',
    'Wyoming': 'WY',
}

In [479]:
StateConversion = pd.DataFrame(StateConversion, index=[0])

In [480]:
StateConversion = pd.melt(frame = StateConversion, var_name = 'State', value_name = 'State_Abbrev')

In [481]:
df4 = pd.merge(left = df3, right = StateConversion, on = 'State', how = 'left')

**Merge remaining datasets**

In [482]:
df5 = pd.merge(left = df4, right = Population, on = ['State_Abbrev', 'Year'], how = 'left')

In [483]:
df6 = pd.merge(left = df5, right = Gas_Prices, on = ['State_Abbrev', 'Year'], how = 'left')

In [484]:
df7 = pd.merge(left = df6, right = Crimes, on = ['State_Abbrev', 'Year'], how = 'left')

In [485]:
df8 = pd.merge(left = df7, right = SPI_Year, on = ['State_Abbrev', 'Year'], how = 'left')

In [486]:
df8.head()

,Year,State,TAVG,TMIN,TMAX,Median_Income,Date,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Astronomical Low Tide,Avalanche,Blizzard,Coastal Flood,Cold/Wind Chill,Debris Flow,Dense Fog,Dense Smoke,Drought,Dust Devil,Dust Storm,Excessive Heat,Extreme Cold/Wind Chill,Flash Flood,Flood,Freezing Fog,Frost/Freeze,Funnel Cloud,HAIL FLOODING,HAIL/ICY ROADS,Hail,Heat,Heavy Rain,Heavy Snow,High Surf,High Wind,Hurricane,Hurricane (Typhoon),Ice Storm,Lake-Effect Snow,Lakeshore Flood,Landslide,Lightning,Marine Dense Fog,Marine Hail,Marine High Wind,Marine Hurricane/Typhoon,Marine Lightning,Marine Strong Wind,Marine Thunderstorm Wind,Marine Tropical Depression,Marine Tropical Storm,Rip Current,Seiche,Sleet,Sneakerwave,Storm Surge/Tide,Strong Wind,THUNDERSTORM WIND/ TREE,THUNDERSTORM WIND/ TREES,THUNDERSTORM WINDS FUNNEL CLOU,THUNDERSTORM WINDS HEAVY RAIN,THUNDERSTORM WINDS LIGHTNING,THUNDERSTORM WINDS/ FLOOD,THUNDERSTORM WINDS/FLASH FLOOD,THUNDERSTORM WINDS/FLOODING,THUNDERSTORM WINDS/HEAVY RAIN,TORNADO/WATERSPOUT,Thunderstorm Wind,Tornado,Tropical Depression,Tropical Storm,Tsunami,Volcanic Ashfall,Waterspout,Wildfire,Winter Storm,Winter Weather,PHYSHLTH,MENTHLTH,State_Abbrev,Population,Gas_Per_Gallon,violent_crime,homicide,rape_legacy,robbery,aggravated_assault,property_crime,burglary,larceny,motor_vehicle_theft,SPI
0,1994,Alabama,63.058333,52.000000,74.083333,27196.0,1994-01-01,273.0,0.0,23.0,0.0,43066050.0,56310000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,152.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.255814,13.930233,AL,4260229.0,1.069864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.275410
1,1994,Alaska,26.191667,18.741667,33.666667,45367.0,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.027132,9.430233,AK,603308.0,1.307750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1994,Arizona,60.550000,46.366667,74.733333,31293.0,1994-01-01,10.0,0.0,0.0,0.0,8310500.0,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.468468,10.387387,AZ,4245089.0,1.193166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.227611
3,1994,Arkansas,60.391667,49.691667,71.091667,25565.0,1994-01-01,10.0,0.0,0.0,0.0,39205850.0,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,425.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,452.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.447489,11.703196,AR,2494019.0,1.073600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.239478
4,1994,California,58.000000,45.391667,70.583333,35331.0,1994-01-01,2.0,0.0,1.0,0.0,7211000.0,50500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.182464,9.693128,CA,31484435.0,1.133383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.065158

**Save year data to csv**

In [487]:
Year_df = df8.copy()

In [488]:
Year_df.to_csv('Year_df.csv')

### Create Month combined dataframe (weather data)

In [500]:
df = pd.merge(left = Weather_Month, right = StateConversion, on = 'State', how = 'left')

In [501]:
df2 = pd.merge(left = df, right = Storm_Month, on = ['Year', 'Month', 'State'], how = 'left')

In [502]:
df3 = pd.merge(left = df2, right = SPI_Month, on = ['Year', 'Month', 'State_Abbrev'], how = 'left')

In [503]:
Month_df = df3.copy()

**Write to csv file**

In [504]:
Month_df.to_csv('Month_df.csv')

In [505]:
Month_df.head()

,Year,Month,State,TAVG,TMIN,TMAX,State_Abbrev,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,Astronomical Low Tide,Avalanche,Blizzard,Coastal Flood,Cold/Wind Chill,Debris Flow,Dense Fog,Dense Smoke,Drought,Dust Devil,Dust Storm,Excessive Heat,Extreme Cold/Wind Chill,Flash Flood,Flood,Freezing Fog,Frost/Freeze,Funnel Cloud,HAIL FLOODING,HAIL/ICY ROADS,Hail,Heat,Heavy Rain,Heavy Snow,High Surf,High Wind,Hurricane,Hurricane (Typhoon),Ice Storm,Lake-Effect Snow,Lakeshore Flood,Landslide,Lightning,Marine Dense Fog,Marine Hail,Marine High Wind,Marine Hurricane/Typhoon,Marine Lightning,Marine Strong Wind,Marine Thunderstorm Wind,Marine Tropical Depression,Marine Tropical Storm,Rip Current,Seiche,Sleet,Sneakerwave,Storm Surge/Tide,Strong Wind,THUNDERSTORM WIND/ TREE,THUNDERSTORM WIND/ TREES,THUNDERSTORM WINDS FUNNEL CLOU,THUNDERSTORM WINDS HEAVY RAIN,THUNDERSTORM WINDS LIGHTNING,THUNDERSTORM WINDS/ FLOOD,THUNDERSTORM WINDS/FLASH FLOOD,THUNDERSTORM WINDS/FLOODING,THUNDERSTORM WINDS/HEAVY RAIN,TORNADO/WATERSPOUT,Thunderstorm Wind,Tornado,Tropical Depression,Tropical Storm,Tsunami,Volcanic Ashfall,Waterspout,Wildfire,Winter Storm,Winter Weather,SPI
0,1994,1,Alabama,40.8,30.8,50.9,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.211791
1,1994,1,Alaska,7.4,1.7,13.1,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1994,1,Arizona,43.2,28.5,57.9,AZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.906000
3,1994,1,Arkansas,36.6,28.0,45.2,AR,0.0,0.0,0.0,0.0,65500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.665333
4,1994,1,California,45.7,34.4,56.9,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.672241